import type { Metadata } from "next";
import localFont from "next/font/local";
import StoreProvider from "@/src/store/StoreProvider";
import "./globals.css";

// import SideBarExpand from "../components/SideBar/SideBarExpand";
import HeaderTop from "../components/header/HeaderTop";
import SideBarMain from "../components/SideBar/SideBarMain";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Shodh AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className="w-full flex">
            <SideBarMain />
            {/* <div className="max-xl:w-[calc(100%-75px)] w-[calc(100%-216px)] max-w flex flex-col justify-start"> */}
            <div className="flex flex-col ">
              <HeaderTop title="Dashboard" name="Kate Mott" />
              <div className="min-h-[calc(100vh-68px)] w-[calc(100vw-75px)] overflow-auto bg-bakground-gradient">
                {children}
              </div>
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
